# Generated by Django 2.1.3 on 2019-01-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('send_time', models.DateTimeField()),
                ('wechat_id', models.CharField(max_length=64)),
                ('response_text', models.TextField(null=True)),
            ],
        ),
    ]
