# Generated by Django 2.1.3 on 2019-01-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
